const { VITE_FREESOUND_API_KEY, VITE_FREESOUND_API_SEARCH_ENDPOINT, VITE_FREESOUND_CLIENTID } = import.meta.env;

export { VITE_FREESOUND_API_KEY, VITE_FREESOUND_API_SEARCH_ENDPOINT, VITE_FREESOUND_CLIENTID };
